version: "3.7"
services:
  % for row in netflow_records:
  netflow_collector:
    image: pmacct/nfacctd:v1.7.5
    external_links:
      - rabbit
    ports:
      - "9996:${port}/udp"
    networks:
      - shared_backend
    volumes:
      - ./conf/netflow/nfacctd.conf:/etc/pmacct/nfacctd.conf
      - ./conf/netflow/pretag.map:/etc/pmacct/pretag.map
  % endfor

  % for row in netflow_records:
  sflow_collector:
    image: pmacct/sfacctd:v1.7.5
    # command: sleep 99999
    # restart: on-failure
    external_links:
      - rabbit
    networks:
      - shared_backend
    ports:
      - "9997:9997/udp"
    volumes:
      - ./conf/sflow/sfacctd.conf:/etc/pmacct/sfacctd.conf
      - ./conf/sflow/pretag.map:/etc/pmacct/pretag.map
  % endfor


networks:
  shared_backend:
    name: shared_backend
    # use a custom driver, with no options
    driver: bridge
